Excercises - Developer II/src/objects/Book__c.object
<CustomObject>
    <description>Test clonevizart</description>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Excercises - Developer II/src/classes/CtrlBooksRest.cls
@RestResource(UrlMapping='/Books/*')
Global class CtrlBooksRest {
    @HttpGet
    global static List<Book__c> getBooks() {
    	RestRequest request = RestContext.request;
    	String bookId = request.params.get('bookId');
    	if(bookId != null) {
	        return [SELECT Id, Name, Unit_Price__c FROM Book__c WHERE Id = :bookId];
    	} else {
    		return [SELECT Id, Name, Unit_Price__c FROM Book__c];
    	}
    }
}